### PR TITLE
Applying XCTest.

### PR DESCRIPTION
**Pull request by jebeomgyeong**
GHUnit is removed. XCTest is applied.

### CODE REVIEW

**Comment by tomaz** [comment]
I don't have facility to test this (no pun intended 😀). But it's "just" unit tests so shouldn't impact the application. Code looks good.

Was it closed by accident or intentionally?

**Comment by jebeomgyeong** [comment]
Actually, it was opened accidentally. I'll open or create PR again after looking into it more carefully by this weekend.

**Comment by tomaz** [comment]
Cool, np, thanks!

**Review by Tanguiano2020 — COMMENTED** [review]
Tapjoy iOS SDK

Tapjoy

Index

 

Hierarchy

 

On This Page 

 	

Jump To… 	  	 	 	Tasks 	 	  	 	  	  	 	 		 		- setBelowConsentAge: 		 		- setSubjectToGDPR: 		 		- setUSPrivacy: 		 		- setUserConsent: 		 	 	 	 

TJPrivacyPolicy Class Reference

Inherits fromNSObjectDeclared inTJPrivacyPolicy.h

– setUserConsent:

– setSubjectToGDPR:

– setBelowConsentAge:

– setUSPrivacy:

Copyright © 2020 Tapjoy. All rights reserved.

Generated by appledoc 2.2.1 (build 1334).

**Review by Tanguiano2020 — COMMENTED** [review]
Tapjoy iOS SDK

Tapjoy

Index

 

Hierarchy

 

On This Page 

 	

Jump To… 	  	 	 	Tasks 	 	  	 	  	  	 	 		 		- setBelowConsentAge: 		 		- setSubjectToGDPR: 		 		- setUSPrivacy: 		 		- setUserConsent: 		 	 	 	 

TJPrivacyPolicy Class Reference

Inherits fromNSObjectDeclared inTJPrivacyPolicy.h

– setUserConsent:

– setSubjectToGDPR:

– setBelowConsentAge:

– setUSPrivacy:

Copyright © 2020 Tapjoy. All rights reserved.

Generated by appledoc 2.2.1 (build 1334).

**Pull request closed without merging**
