### PR TITLE
Fixing Safari 8 arrow issue

### PR DESCRIPTION
**Pull request by hybridcattt**
Fixing #578

### CODE REVIEW

**Comment by hybridcattt** [comment]
@tomaz Could you please take a look at this? I think checks failed due to some other error.

**Comment by tomaz** [comment]
Sorry for late reply, for some reason I missed all pull requests since december 8|

All is fine, merging this now.

Don't worry about the checks - those are meant to development branch. Which brings me to http://www.gentlebytes.com/blog/2015/11/02/appledoc-contributors-needed/ - if you'd like to contribute to next major version, let me know and I can add you to the team!

**Comment by hybridcattt** [comment]
@tomaz I shot you a message via the contact form on gentlebytes.com.

**Comment by tomaz** [comment]
Thanks, saw it, will add you to appledoc groups shortly

**Pull request merged**
