### PR TITLE
Versioning dependencies

### PR DESCRIPTION
**Pull request by Coeur**
Using CocoaPods 1.0.0 beta 8 for ParseKit, RegexKitLite, GRMustache.
Currently, there should be no impact, as I tried to use the closest matching source. But testing is recommended.
We can update the pods individually afterward.

### CODE REVIEW

**Comment by tomaz** [comment]
Is this ready for merge or still work in progress?

**Comment by Coeur** [comment]
This part is ready. But you can wait for all third parties to be done to avoid multiple pulls and merges. I will continue this branch on Saturday/Sunday.

**Comment by tomaz** [comment]
Ok, no problem, will wait till all is done. Thanks!

**Comment by Coeur** [comment]
All three static libraries (ParseKit, Discount, GRMustache) are now built from source. @tomaz, could you check if the build time of a fresh installation of Appledoc is not too much affected? And do a smoke test that things are working as they should?

Note that for Discount, I configured it with default values. But doc suggests that libmarkdown.a could have been previously configured with:

    --enable-superscript	A^B expands to A<sup>B</sup>
    --relaxed-emphasis	Don't treat _ in the middle of a word as emphasis
    --with-tabstops=N	Set tabstops to N characters (default is 4)

I assumed those were not used and I didn't check.

**Comment by tomaz** [comment]
I would't worry about build speed, I'll prepare prebuilt binary after this change anyway. The problem with current version (and one of the reasons for pushing 3.0) is lack of unit tests coverage; makes it very hard to prevent regressions... Changes you're making are affecting large portions of the app, but on the other hand the solutions they provide should not be altered that much or even at all. So don't worry too much, push on and we'll deal with problems afterwards. Thanks!

**Pull request merged**
