### PR TITLE
Implement updated template to match the Xcode 6 docs.

### PR DESCRIPTION
**Pull request by kirb**
I don't know whether you would like the template updated to match Xcode 6's documentation, but I decided I'd go ahead and update it myself. 

As far as I know everything is exact to how it is in the original docs. However, I chose to not implement the table of contents sidebar - I have to move on to my next project as soon as possible and I didn't personally find it important if there's already a "jump to" dropdown.

~~Unfortunately, jumping to a section via the dropdown will scroll it under the top bars. Not a problem in Xcode since they're hidden there. Could be fixed in JavaScript, but again, I don't really have time to fix this.~~

The CSS is preprocessed by [Sass](http://sass-lang.com/) with `--style compressed`, and should also be run through [autoprefixer](https://github.com/postcss/autoprefixer); I don't know how you want to go about adding this to the build process so I'll leave that to you.

Tested in Chrome, Safari, Dash, and Xcode. (Note that I've changed my OS X system font; the docs will usually be in Helvetica Neue.) Dash seems to not load JavaScript?

Live example: https://hbang.github.io/libcephei / https://hbang.github.io/libcephei/xcode-docset.atom

image
image
image

### CODE REVIEW

**Comment by tomaz** [comment]
This is awesome, thanks!!!! I'm not much of a html/css/javascript lover, so templates definitely didn't receive much needed attention...

**Comment by Kapeli** [comment]
> Dash seems to not load JavaScript?

If you want Dash to load `.js` files, see http://kapeli.com/docsets#enableJavascript.

Can you also add a class to the `<body>` tag, something like `<body class="appledoc">`? This will allow me to add some custom styling to Dash's stylesheet to make it work better with the new template.

**Comment by kirb** [comment]
Aha, didn't think to check your site, thanks! Do you think it'd be worth enabling the JS though? At most it's just extra CSS and some features Dash doesn't need (the jump-to and toggling the method detail which I [disable](https://github.com/tomaz/appledoc/blob/master/Templates/html/css/scss/_xcode.scss) anyway).

Thanks for your work!

**Comment by Kapeli** [comment]
As far as I can tell, no, no need to enable JavaScript.

**Comment by tomaz** [comment]
@kirb Just checking - do you plan to update templates as indicated by @Kapeli above? If it's just adding class to body tag and key for enabling JavaScript, it's trivial and even I can do it :) Otherwise I'd leave it to you if that's ok...

@Kapeli Is the name of the body class important for Dash? Can it be `"appledoc"` or do you use it for some kind of versioning?

**Comment by kirb** [comment]
I can leave that to you; just the body class needs to be done. I think he wants the appledoc-new class because of the classes/styles being different from what they were in the previous template, given Dash hides everything but the content.

**Comment by Kapeli** [comment]
@tomaz @kirb It can be just `appledoc`, it would be fine for Dash.

There's no need to enable JavaScript right now.

**Comment by tomaz** [comment]
Updated templates, body tag uses "appledoc" class now.

**Comment by Kapeli** [comment]
Can you add the class to document-, hierarchy- and index-template as well? Basically I want all the pages to have that class so if I add a new style (e.g. something that hides the floating menu at the top), it gets applied everywhere.

**Comment by tomaz** [comment]
There you go, also bumping up version to 2.2.1

**Comment by Kapeli** [comment]
Thank you! :+1:

**Comment by sixten** [comment]
> The CSS is preprocessed by Sass with --style compressed, and should also be run through autoprefixer; I don't know how you want to go about adding this to the build process so I'll leave that to you.

@kirb does this mean that the code in the templates needs to be run through Sass as part of the process of building appledoc's output? And that your code that @tomaz merged doesn't do that step?

(This seems to be the case, given that the output I get from the code at HEAD still has `.scss` files in it.)

**Comment by kirb** [comment]
@sixten At the moment yes, or you can just grab it from me: https://hbang.github.io/libcephei/css/style.css.

**Comment by ryanjm** [comment]
Wish I had found that css file issue 3 hours ago. :) Finally got styling working, but no titles.

**Pull request merged**
