### PR TITLE
updating minizip, regexkitlite, OCMock

### PR DESCRIPTION
**Pull request by Coeur**
may need testing

### CODE REVIEW

**Comment by Coeur** [comment]
Oh, don't merge, DDMinizip doesn't build with latest minizip. I'll investigate.

**Comment by Coeur** [comment]
I've cloned DDMinizip, made it compatible with latest minizip, and used it as a pod

**Comment by tomaz** [comment]
Thanks, looks good on quick inspection. Travelling till friday, will take closer look in following days as I get more time!

**Comment by tomaz** [comment]
Looks good, merging, thanks @Coeur!

**Pull request merged**
